// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaeqkgjhgdykxwjkaxpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZXFrZ2poZ2R5a3h3amtheHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MjI2NDUsImV4cCI6MjA4NjI5ODY0NX0.kA6Uh3mY_ZPE_HVwMvdbb61X-iU3XF7XIAKTUoDKm60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});